### ISSUE TITLE
Beware of delayed bans

### ISSUE THREAD

**Issue by bugproof** [CasualX/apexbot#10]
Just to inform you EAC busted me for using this slightly modified bot. My communication method is UD, so most likely got busted for glow or SendInput which the bot uses and EAC scanned the binary. Or it's sigged already.

**Comment by CasualX** [comment]
That's unfortunate but also somewhat expected. Releasing source code makes it slightly harder but not impossible to sig.

You can try changing compiler settings (optimize for size instead of speed) but there may be constants and string literal that give it away. I tried to avoid them but I didn't put too much effort in it.

This code is an old incomplete port of my own bot written in Rust and I'm using my own bypass + write glow + sendinput and I'm not banned.
