### ISSUE TITLE
Fatal Error: winternl.h: No such file or directory

### ISSUE THREAD

**Issue by SkyBoltDom** [CasualX/apexbot#7]
I'm compiling with MinGW64 in powershell without administrative access, and process.cpp has been written to include winternl.h which does not exist in my system. Should I delete the line? Oh yeah and by the way I compiled using the stdafx.cpp

**Comment by CasualX** [comment]
winternl.h is a header provided by the Windows SDK. I don't know why MinGW has issues with it. Perhaps try reinstalling the Windows SDK explicitly?

It is used to [enumerate the processes](https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntquerysysteminformation), mostly because I like the API better than the toolhelp32snapshot API. You can replace this API with another implementation if needed.

**Comment by SkyBoltDom** [comment]
Okay I will try that

**Comment by SkyBoltDom** [comment]
Okay so it is downloading but I thought I downloaded it with visual studio so that is kind of odd

**Comment by SkyBoltDom** [comment]
no I am still getting the error

**Comment by CasualX** [comment]
When I search for [mingw winternl.h](https://www.google.com/search?q=mingw+winternl.h) the links are telling me that it should work for 64-bit builds. Try building as a 64-bit application?

**Comment by SkyBoltDom** [comment]
ok

**Comment by SkyBoltDom** [comment]
oh no I downloaded 32 bit before on accident so i have to install 64

**Comment by SkyBoltDom** [comment]
its just not working
